### ISSUE TITLE
Add topic tags `cuda-fortran`, `cuda`

### ISSUE THREAD

**Issue by Beliavsky** [wsyip85/CUDA-FORTRAN#1]
I suggest adding the topics `cuda-fortran`, `cuda` in the About section, as explained at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by wsyip85** [comment]
I will close this issue. Thank you for highlighting it.
